### ISSUE TITLE
Merge sort

### ISSUE THREAD

**Issue by devjak26** [manan025/DS-Algo-Zone#213]
## 🚀 Feature

 merge sort is an efficient, and comparison-based sorting algorithm.

### Have you read the Contribution Guidelines?

 YES

## Pitch

 Merge sort is one of the most efficient sorting algorithms. It works on the principle of Divide and Conquers.

## Assignees

(Do not make changes in this section until asked to do so)  
C -  
C# -  
C++ -   
Go -  
Java -  
Javascript -  
Kotlin -  
Python -

**Comment by devjak26** [comment]
@manan025  i want to work in c++

**Comment by Aditya01237** [comment]
i want to work on java

**Comment by shashank-suresh** [comment]
Could I work on this in C?

**Comment by 99anjali** [comment]
please assign me .I want to work using python

**Comment by Sejal253** [comment]
I want to work using javascript

**Comment by manan025** [comment]
#60 duplicate
