### ISSUE TITLE
Some famous interview questions are missing. Please assign me this, i will do it asap

### ISSUE THREAD

**Issue by rushikeshadhav** [manan025/DS-Algo-Zone#234]
## 🚀 Feature

(Write down a clear and concise description of what the feature is.)

### Have you read the Contribution Guidelines?

(Write your answer here.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
These questions needs to be addedd
Majority element
Rat in a maze
Pascal's triangle

## Assignees

(Do not make changes in this section until asked to do so)  
C -  
C# -  
C++ -   
Go -  
Java -  
Javascript -  
Kotlin -  
Python -

**Comment by tm2k23** [comment]
Pascal's triangle is there

**Comment by rushikeshadhav** [comment]
Ok I will add these more problems
Median of two sorted arrays of different sizes
Allocate minimum number of pages
Longest Palindrome in a string

**Comment by manan025** [comment]
Create individual issues for algorithms.
