### ISSUE TITLE
Could work on adding few More Searching and sorting algo

### ISSUE THREAD

**Issue by Manogya08** [manan025/DS-Algo-Zone#25]

**Comment by manan025** [comment]
@Manogya08 Sure, make sure you make issue for the particular sorting algorithm and once you are assigned with a programming language, you can create PR for that issue.
Also, make sure you make different PRs for different issues/ programming languages.

**Comment by jagritvats** [comment]
Can I work on Linear Search in CPP?

**Comment by manan025** [comment]
@jagritvats sure, I'll create issue for Linear Search and assign you.

**Comment by SurendarSingh** [comment]
@manan025 spiral order matrix traversal
If this issue can be created, assign me c++

**Comment by manan025** [comment]
@SurendarSingh you can create issue for the same. I'll assign it to you.
